-- ============================================================================
-- Migration Script: Refactor Budget (Presupuesto) Schema
-- ============================================================================
-- Purpose: Remove invoice (factura) references from budget tables and
--          replace with proper budget (presupuesto) naming conventions
-- Date: 2025-11-24
-- ============================================================================

USE subocasana;

-- ============================================================================
-- STEP 1: Rename columns in suboc_presupuestos (Budget Header Table)
-- ============================================================================

ALTER TABLE `suboc_presupuestos`
  CHANGE COLUMN `NRO_FACTURA` `NRO_PRESUPUESTO` int(8) NOT NULL,
  CHANGE COLUMN `SERIE_FACTURA` `SERIE_PRESUPUESTO` varchar(8) NOT NULL,
  CHANGE COLUMN `CODIGO_CLIENTE_FACTURA` `CODIGO_CLIENTE_PRESUPUESTO` varchar(10) DEFAULT NULL,
  CHANGE COLUMN `RAZONSOCIAL_CLIENTE_FACTURA` `RAZONSOCIAL_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `NIF_CLIENTE_FACTURA` `NIF_CLIENTE_PRESUPUESTO` varchar(50) DEFAULT NULL,
  CHANGE COLUMN `MOVIL_CLIENTE_FACTURA` `MOVIL_CLIENTE_PRESUPUESTO` varchar(40) DEFAULT NULL,
  CHANGE COLUMN `EMAIL_CLIENTE_FACTURA` `EMAIL_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `DIRECCION1_CLIENTE_FACTURA` `DIRECCION1_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `DIRECCION2_CLIENTE_FACTURA` `DIRECCION2_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `POBLACION_CLIENTE_FACTURA` `POBLACION_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `PROVINCIA_CLIENTE_FACTURA` `PROVINCIA_CLIENTE_PRESUPUESTO` varchar(200) DEFAULT NULL,
  CHANGE COLUMN `CPOSTAL_CLIENTE_FACTURA` `CPOSTAL_CLIENTE_PRESUPUESTO` varchar(15) DEFAULT NULL,
  CHANGE COLUMN `PAIS_CLIENTE_FACTURA` `PAIS_CLIENTE_PRESUPUESTO` varchar(150) DEFAULT NULL,
  CHANGE COLUMN `TIPOID_INT_CLIENTE_FACTURA` `TIPOID_INT_CLIENTE_PRESUPUESTO` varchar(20) DEFAULT NULL COMMENT '''ID'' O ''PASAPORTE'' PARA EL TIPO DE IDENTIFICACIÓN INTERNACIONAL',
  CHANGE COLUMN `FECHA_FACTURA` `FECHA_PRESUPUESTO` date DEFAULT NULL,
  CHANGE COLUMN `TOTAL_LIQUIDO_FACTURA` `TOTAL_LIQUIDO_PRESUPUESTO` decimal(18,6) DEFAULT NULL COMMENT 'Total Presupuesto',
  CHANGE COLUMN `FORMA_PAGO_FACTURA` `FORMA_PAGO_PRESUPUESTO` varchar(200) DEFAULT NULL COMMENT 'Codigo Forma de Pago',
  CHANGE COLUMN `COMENTARIOS_FACTURA` `COMENTARIOS_PRESUPUESTO` text DEFAULT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`SERIE_PRESUPUESTO`, `NRO_PRESUPUESTO`) USING BTREE;

-- ============================================================================
-- STEP 2: Rename columns in suboc_presupuestos_lineas (Budget Lines Table)
-- ============================================================================

ALTER TABLE `suboc_presupuestos_lineas`
  CHANGE COLUMN `SERIE_FACTURA_LINEA` `SERIE_PRESUPUESTO_LINEA` varchar(8) NOT NULL,
  CHANGE COLUMN `NRO_FACTURA_LINEA` `NRO_PRESUPUESTO_LINEA` int(8) NOT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`SERIE_PRESUPUESTO_LINEA`, `NRO_PRESUPUESTO_LINEA`, `LINEA_LINEA`) USING BTREE;

-- ============================================================================
-- STEP 3: Rename columns in suboc_dibujos_presupuestos (Budget Drawings Table)
-- ============================================================================

ALTER TABLE `suboc_dibujos_presupuestos`
  CHANGE COLUMN `NRO_FACTURA` `NRO_PRESUPUESTO` int(8) NOT NULL,
  CHANGE COLUMN `SERIE_FACTURA` `SERIE_PRESUPUESTO` varchar(8) NOT NULL,
  CHANGE COLUMN `DIBUJO_FACTURA` `DIBUJO_PRESUPUESTO` longblob DEFAULT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (`NRO_PRESUPUESTO`, `SERIE_PRESUPUESTO`) USING BTREE;

-- ============================================================================
-- STEP 4: Update Stored Procedure - PRC_CALCULAR_PRESUPUESTO
-- ============================================================================

DROP PROCEDURE IF EXISTS `PRC_CALCULAR_PRESUPUESTO`;

DELIMITER //

CREATE PROCEDURE `PRC_CALCULAR_PRESUPUESTO`(
  IN `pidseriepresupuesto` VARCHAR(8),
  IN `pidnumpresupuesto` INT
)
BEGIN
  UPDATE suboc_presupuestos
  SET TOTAL_LIQUIDO_PRESUPUESTO = (
    SELECT SUM(SUM_TOTAL_LINEA)
    FROM suboc_presupuestos_lineas
    WHERE SERIE_PRESUPUESTO_LINEA = pidseriepresupuesto
      AND NRO_PRESUPUESTO_LINEA = pidnumpresupuesto
  )
  WHERE SERIE_PRESUPUESTO = pidseriepresupuesto
    AND NRO_PRESUPUESTO = pidnumpresupuesto;
END //

DELIMITER ;

-- ============================================================================
-- STEP 5: Update Stored Procedure - PRC_CREAR_RECIBOS_PRESUPUESTO
-- ============================================================================

DROP PROCEDURE IF EXISTS `PRC_CREAR_RECIBOS_PRESUPUESTO`;

DELIMITER //

CREATE PROCEDURE `PRC_CREAR_RECIBOS_PRESUPUESTO`(
  IN `pSERIE_PRESUPUESTO` VARCHAR(8),
  IN `pNRO_PRESUPUESTO` INT,
  IN `pCODIGO_FORMA_PAGO` VARCHAR(20),
  IN `pNUMERO_MESES` INT,
  IN `pPRIMER_VENCIMIENTO` DATE
)
BEGIN
  DECLARE importeporcuota DECIMAL(18,6);
  DECLARE codtipopago VARCHAR(20);
  DECLARE contador INT DEFAULT 1;

  SET importeporcuota = (
    SELECT TOTAL_LIQUIDO_PRESUPUESTO / pNUMERO_MESES
    FROM suboc_presupuestos
    WHERE SERIE_PRESUPUESTO = pSERIE_PRESUPUESTO
      AND NRO_PRESUPUESTO = pNRO_PRESUPUESTO
  );

  WHILE contador <= pNUMERO_MESES DO
    INSERT INTO suboc_recibos_presupuestos(
      SERIE_PRESUPUESTO_REC,
      NRO_PRESUPUESTO_REC,
      NUMERO_RECIBO,
      FECHA_VENCIMIENTO,
      IMPORTE,
      CODIGO_FORMA_PAGO_RECIBO,
      ESTADO_RECIBO
    ) VALUES (
      pSERIE_PRESUPUESTO,
      pNRO_PRESUPUESTO,
      contador,
      DATE_ADD(pPRIMER_VENCIMIENTO, INTERVAL (contador - 1) MONTH),
      importeporcuota,
      pCODIGO_FORMA_PAGO,
      'PENDIENTE'
    );
    SET contador = contador + 1;
  END WHILE;
END //

DELIMITER ;

-- ============================================================================
-- STEP 6: Update Function - FNC_GET_NEXT_LINEA_PRESUPUESTO
-- ============================================================================

DROP FUNCTION IF EXISTS `FNC_GET_NEXT_LINEA_PRESUPUESTO`;

DELIMITER //

CREATE FUNCTION `FNC_GET_NEXT_LINEA_PRESUPUESTO`(
  `pSERIE_PRESUPUESTO` VARCHAR(8),
  `pNRO_PRESUPUESTO` INT
) RETURNS VARCHAR(3) CHARSET utf8mb4 COLLATE utf8mb4_spanish_ci
BEGIN
  DECLARE vNextLinea INT;

  SELECT COALESCE(MAX(CAST(LINEA_LINEA AS UNSIGNED)), 0) + 10
  INTO vNextLinea
  FROM suboc_presupuestos_lineas
  WHERE SERIE_PRESUPUESTO_LINEA = pSERIE_PRESUPUESTO
    AND NRO_PRESUPUESTO_LINEA = pNRO_PRESUPUESTO;

  RETURN LPAD(vNextLinea, 3, '0');
END //

DELIMITER ;

-- ============================================================================
-- STEP 7: Update Stored Procedure - PRC_CREAR_FACTURA_PRESUPUESTO
-- ============================================================================
-- This procedure converts a budget to an invoice, so it reads from presupuesto
-- tables (with new column names) and writes to factura tables

DROP PROCEDURE IF EXISTS `PRC_CREAR_FACTURA_PRESUPUESTO`;

DELIMITER //

CREATE PROCEDURE `PRC_CREAR_FACTURA_PRESUPUESTO`(
  IN `pSERIE_PRESUPUESTO` VARCHAR(8),
  IN `pNRO_PRESUPUESTO` INT,
  IN `pSERIE_FACTURA` VARCHAR(8),
  OUT `pNRO_FACTURA` INT
)
BEGIN
  DECLARE done INT DEFAULT FALSE;
  DECLARE vCODIGO_CLIENTE VARCHAR(10);
  DECLARE vRAZONSOCIAL_CLIENTE VARCHAR(200);
  DECLARE vNIF_CLIENTE VARCHAR(50);
  DECLARE vMOVIL_CLIENTE VARCHAR(40);
  DECLARE vEMAIL_CLIENTE VARCHAR(200);
  DECLARE vDIRECCION1_CLIENTE VARCHAR(200);
  DECLARE vDIRECCION2_CLIENTE VARCHAR(200);
  DECLARE vPOBLACION_CLIENTE VARCHAR(200);
  DECLARE vPROVINCIA_CLIENTE VARCHAR(200);
  DECLARE vCPOSTAL_CLIENTE VARCHAR(15);
  DECLARE vPAIS_CLIENTE VARCHAR(150);
  DECLARE vTIPOID_INT_CLIENTE VARCHAR(20);
  DECLARE vFECHA DATE;
  DECLARE vFORMA_PAGO VARCHAR(200);
  DECLARE vCOMENTARIOS TEXT;
  DECLARE vNOMBRE VARCHAR(100);
  DECLARE vAPELLIDOS VARCHAR(100);

  DECLARE vLINEA VARCHAR(3);
  DECLARE vCODIGO_ARTICULO VARCHAR(20);
  DECLARE vDESCRIPCION_ARTICULO VARCHAR(100);
  DECLARE vZONA VARCHAR(60);
  DECLARE vPRECIOVENTA DECIMAL(19,6);
  DECLARE vCANTIDAD DECIMAL(18,6);
  DECLARE vSUM_TOTAL DECIMAL(19,6);
  DECLARE vODONTOLOGO VARCHAR(8);

  DECLARE cur_lineas CURSOR FOR
    SELECT LINEA_LINEA, CODIGO_ARTICULO_LINEA, DESCRIPCION_ARTICULO_LINEA,
           ZONA, PRECIOVENTA_ARTICULO_LINEA, CANTIDAD_LINEA,
           SUM_TOTAL_LINEA, ODONTOLOGO
    FROM suboc_presupuestos_lineas
    WHERE SERIE_PRESUPUESTO_LINEA = pSERIE_PRESUPUESTO
      AND NRO_PRESUPUESTO_LINEA = pNRO_PRESUPUESTO;

  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

  -- Get budget header data
  SELECT CODIGO_CLIENTE_PRESUPUESTO, RAZONSOCIAL_CLIENTE_PRESUPUESTO,
         NIF_CLIENTE_PRESUPUESTO, MOVIL_CLIENTE_PRESUPUESTO,
         EMAIL_CLIENTE_PRESUPUESTO, DIRECCION1_CLIENTE_PRESUPUESTO,
         DIRECCION2_CLIENTE_PRESUPUESTO, POBLACION_CLIENTE_PRESUPUESTO,
         PROVINCIA_CLIENTE_PRESUPUESTO, CPOSTAL_CLIENTE_PRESUPUESTO,
         PAIS_CLIENTE_PRESUPUESTO, TIPOID_INT_CLIENTE_PRESUPUESTO,
         FECHA_PRESUPUESTO, FORMA_PAGO_PRESUPUESTO,
         COMENTARIOS_PRESUPUESTO, NOMBRE, APELLIDOS
  INTO vCODIGO_CLIENTE, vRAZONSOCIAL_CLIENTE, vNIF_CLIENTE,
       vMOVIL_CLIENTE, vEMAIL_CLIENTE, vDIRECCION1_CLIENTE,
       vDIRECCION2_CLIENTE, vPOBLACION_CLIENTE, vPROVINCIA_CLIENTE,
       vCPOSTAL_CLIENTE, vPAIS_CLIENTE, vTIPOID_INT_CLIENTE,
       vFECHA, vFORMA_PAGO, vCOMENTARIOS, vNOMBRE, vAPELLIDOS
  FROM suboc_presupuestos
  WHERE SERIE_PRESUPUESTO = pSERIE_PRESUPUESTO
    AND NRO_PRESUPUESTO = pNRO_PRESUPUESTO;

  -- Get next invoice number
  SET pNRO_FACTURA = GET_NEXT_CONT_FACT_SERIE(pSERIE_FACTURA, 'FC');

  -- Create invoice header
  INSERT INTO suboc_facturas(
    NRO_FACTURA, SERIE_FACTURA, CODIGO_CLIENTE_FACTURA,
    RAZONSOCIAL_CLIENTE_FACTURA, NIF_CLIENTE_FACTURA,
    MOVIL_CLIENTE_FACTURA, EMAIL_CLIENTE_FACTURA,
    DIRECCION1_CLIENTE_FACTURA, DIRECCION2_CLIENTE_FACTURA,
    POBLACION_CLIENTE_FACTURA, PROVINCIA_CLIENTE_FACTURA,
    CPOSTAL_CLIENTE_FACTURA, PAIS_CLIENTE_FACTURA,
    TIPOID_INT_CLIENTE_FACTURA, FECHA_FACTURA,
    FORMA_PAGO_FACTURA, COMENTARIOS_FACTURA,
    NOMBRE, APELLIDOS
  ) VALUES (
    pNRO_FACTURA, pSERIE_FACTURA, vCODIGO_CLIENTE,
    vRAZONSOCIAL_CLIENTE, vNIF_CLIENTE, vMOVIL_CLIENTE,
    vEMAIL_CLIENTE, vDIRECCION1_CLIENTE, vDIRECCION2_CLIENTE,
    vPOBLACION_CLIENTE, vPROVINCIA_CLIENTE, vCPOSTAL_CLIENTE,
    vPAIS_CLIENTE, vTIPOID_INT_CLIENTE, CURDATE(),
    vFORMA_PAGO, vCOMENTARIOS, vNOMBRE, vAPELLIDOS
  );

  -- Copy budget lines to invoice lines
  OPEN cur_lineas;

  read_loop: LOOP
    FETCH cur_lineas INTO vLINEA, vCODIGO_ARTICULO, vDESCRIPCION_ARTICULO,
                          vZONA, vPRECIOVENTA, vCANTIDAD, vSUM_TOTAL, vODONTOLOGO;

    IF done THEN
      LEAVE read_loop;
    END IF;

    INSERT INTO suboc_facturas_lineas(
      SERIE_FACTURA_LINEA, NRO_FACTURA_LINEA, LINEA_LINEA,
      CODIGO_ARTICULO_LINEA, DESCRIPCION_ARTICULO_LINEA,
      ZONA, PRECIOVENTA_ARTICULO_LINEA, CANTIDAD_LINEA,
      SUM_TOTAL_LINEA, ODONTOLOGO
    ) VALUES (
      pSERIE_FACTURA, pNRO_FACTURA, vLINEA,
      vCODIGO_ARTICULO, vDESCRIPCION_ARTICULO,
      vZONA, vPRECIOVENTA, vCANTIDAD,
      vSUM_TOTAL, vODONTOLOGO
    );
  END LOOP;

  CLOSE cur_lineas;

  -- Calculate invoice totals
  CALL PRC_CALCULAR_FACTURA(pSERIE_FACTURA, pNRO_FACTURA);
END //

DELIMITER ;

-- ============================================================================
-- STEP 8: Update View - v_suboc_presupuestos
-- ============================================================================

DROP VIEW IF EXISTS `v_suboc_presupuestos`;

CREATE VIEW `v_suboc_presupuestos` AS
SELECT
  p.NRO_PRESUPUESTO,
  p.SERIE_PRESUPUESTO,
  p.CODIGO_CLIENTE_PRESUPUESTO,
  p.RAZONSOCIAL_CLIENTE_PRESUPUESTO,
  p.NIF_CLIENTE_PRESUPUESTO,
  p.MOVIL_CLIENTE_PRESUPUESTO,
  p.EMAIL_CLIENTE_PRESUPUESTO,
  p.DIRECCION1_CLIENTE_PRESUPUESTO,
  p.DIRECCION2_CLIENTE_PRESUPUESTO,
  p.POBLACION_CLIENTE_PRESUPUESTO,
  p.PROVINCIA_CLIENTE_PRESUPUESTO,
  p.CPOSTAL_CLIENTE_PRESUPUESTO,
  p.PAIS_CLIENTE_PRESUPUESTO,
  p.TIPOID_INT_CLIENTE_PRESUPUESTO,
  p.FECHA_PRESUPUESTO,
  p.TOTAL_LIQUIDO_PRESUPUESTO,
  p.FORMA_PAGO_PRESUPUESTO,
  p.COMENTARIOS_PRESUPUESTO,
  p.NOMBRE,
  p.APELLIDOS,
  d.DIBUJO_PRESUPUESTO
FROM suboc_presupuestos p
LEFT JOIN suboc_dibujos_presupuestos d
  ON p.SERIE_PRESUPUESTO = d.SERIE_PRESUPUESTO
  AND p.NRO_PRESUPUESTO = d.NRO_PRESUPUESTO;

-- ============================================================================
-- Migration Complete
-- ============================================================================

SELECT 'Budget schema refactoring completed successfully!' AS Status;
